### ISSUE TITLE
hugo build incorrect path for css

### ISSUE THREAD

**Issue by supercaizehua** [athul/archie#1]
incorrect path in public/index.html
line 19
![image](https://user-images.githubusercontent.com/33114810/79626869-528f6d00-8166-11ea-98e4-e9b065beddd0.png)

and after deployment, my github page look like this 
![image](https://user-images.githubusercontent.com/33114810/79626884-794da380-8166-11ea-8c97-901bddd8d6df.png)

after I fix the path, everything is ok

**Comment by supercaizehua** [comment]
![image](https://user-images.githubusercontent.com/33114810/79626938-d5b0c300-8166-11ea-9486-95e6c07fbd0c.png)

**Comment by athul** [comment]
Hey, Thanks for opening the issue. Can you share your `config` file.

**Comment by supercaizehua** [comment]
https://github.com/supercaizehua/blog-resources/tree/master/supercaizehua

**Comment by athul** [comment]
Just add a trailing `/ `  to your baseURL

https://github.com/supercaizehua/blog-resources/blob/d3bd36db7929acb8558afb6cf314c4f429bb0496/supercaizehua/config.toml#L1

**Comment by supercaizehua** [comment]
problem solved
