### ISSUE TITLE
Mermaid diagram problem

### ISSUE THREAD

**Issue by GGuinea** [athul/archie#101]
Hi!

Does anyone make mermaid diagrams working with this theme? I've recently tried with either the official docs https://gohugo.io/content-management/diagrams/ or some others from google but it doesn't work properly. Basically diagram is renders so small. 
<img width="885" alt="image" src="https://github.com/athul/archie/assets/44040042/ce798d3c-cb7f-425b-98ec-b185394bf39f">

**Comment by jmooring** [comment]
<https://discourse.gohugo.io/t/mermaid-diagram-problem/47761/2?u=jmooring>

**Comment by GGuinea** [comment]
Thank you!
