### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by athul** [athul/archie#13]
Currently the Light Mode to Dark mode switching is based on system theme. Implementing a Toggle would be easier for users to switch between the theme.

**Comment by Spoon-8285** [comment]
can i do this?

**Comment by athul** [comment]
Sure

**Comment by martinbaillie** [comment]
This would be great @Spoon-8285! It is always nice to give the user a choice on top of the OS-inferred
c.f. https://hankchizljaw.com/wrote/create-a-user-controlled-dark-or-light-mode/

**Comment by yhau1989** [comment]
![2020-10-23_02 01 09](https://user-images.githubusercontent.com/12787927/96967191-bbb8ba00-14d4-11eb-82a1-46b42ec12a04.gif)
I worked in a demo

**Comment by yhau1989** [comment]
@athul review my pull request f2032af4d998e5eb41e01c24014e0db22d81c343

> ![2020-10-23_02 01 09](https://user-images.githubusercontent.com/12787927/96967191-bbb8ba00-14d4-11eb-82a1-46b42ec12a04.gif)
> I worked in a demo

@athul review my pull request f2032af4d998e5eb41e01c24014e0db22d81c343

**Comment by joaopgrassi** [comment]
I'm more of a fan of icons like this: 
![image](https://user-images.githubusercontent.com/5938087/97559352-9ac4fd00-19dd-11eb-9933-650175bc4f05.png)
https://adityatelange.github.io/hugo-PaperMod/

**Comment by yhau1989** [comment]
awesome @joaopgrassi :+1:

**Comment by RobbiNespu** [comment]
> Currently the Light Mode to Dark mode switching is based on system theme. Implementing a Toggle would be easier for users to switch between the theme.

Take a look on https://github.com/googlechromelabs/dark-mode-toggle
Some fork implement it well, but it not clean commit
https://github.com/fma16/archie/commit/dad5309dca646bb4aa82d140a46fe8a7b6996565
https://github.com/fma16/archie/commit/7fbeb6019c7193216b2a834889cab317ae597ae8
https://github.com/fma16/archie/commit/5c07b046e930778c794c6af74e73f07a62d6712c
https://github.com/fma16/archie/commit/2148118607d8f6ebfbfc63ef7fe06ac00b67a44a

Demo : his website https://lawgier.net/ (toggle at the bottom)

**Comment by RobbiNespu** [comment]
If anyone interested, take look on https://github.com/RobbiNespu/archie/pull/4/files it worked well when you are using light mode manual or light mode manual

My code are messy, someone good with js and css maybe can do better

**Comment by athul** [comment]
> If anyone interested, take look on https://github.com/RobbiNespu/archie/pull/4/files it worked well when you are using light mode manual or light mode manual
> 
> My code are messy, someone good with js and css maybe can do better
> 

Hey, this is cool. I loved the Minimal Js Setup. Is it possible to show a deployed version of the same? Thanks

**Comment by RobbiNespu** [comment]
> 
> 
> > If anyone interested, take look on https://github.com/RobbiNespu/archie/pull/4/files it worked well when you are using light mode manual or light mode manual
> > My code are messy, someone good with js and css maybe can do better
> 
> Hey, this is cool. I loved the Minimal Js Setup. Is it possible to show a deployed version of the same? Thanks

I dont have live deploy version but a gif should be ok?

![](https://i.vgy.me/mbUVGN.gif)

I keep upstream (master) on my fork and do changes on other branch on my repo. So that why the screenshot look different, but the base and the file that should be patch are same

**Comment by athul** [comment]
Looks Clean. Could you send a PR with the current changes. I will review it and merge it 😄. 

The Feather icon dependancy could be updated since people might not use the feather icons in their site, so making feather an optional dependency would be great.

**Comment by RobbiNespu** [comment]
Should we let it until upcoming hacktoberfest? But if you want, I can send PR with base from upstream (your master) when I free later.

For Feather icon, yeah.. I also posted my idea here https://github.com/athul/archie/discussions/26

**Comment by athul** [comment]
Why Hacktoberfest? Is there anything specific for waiting till Hacktoberfest?

**Comment by RobbiNespu** [comment]
> 
> 
> Why Hacktoberfest? Is there anything specific for waiting till Hacktoberfest?

You put a label for hacktoberfest there :)

**Comment by athul** [comment]
> > 
> > 
> > Why Hacktoberfest? Is there anything specific for waiting till Hacktoberfest?
> 
> You put a label for hacktoberfest there :)

Forgot about it. Never mind about that. If you're free send the PR😄

**Comment by RobbiNespu** [comment]
@athul , I sending my patch for this issue on #30 PR

**Comment by RobbiNespu** [comment]
> Hello all,
> 
> I saw that @RobbiNespu did manage to fix this on his [webpage](https://robbinespu.gitlab.io/), so it is not clear to me why this has not been implemented yet. I tried to follow the changes he suggested, and I do get a button that works, but the icon does not change to Moon when using the dark mode.
> 
> May I ask what is the current status of this issue?
> 
> Thanks in advance, George.

Try check discussion on #30

As for now, my implementation won't work when page initially load as dark mode (either config as permanent dark or auto), because my understanding "dark mode" is for turning light-to-dark, not dark-to-light-to-dark 

(but actually, it can be done by flip and switch the *.css + load js. That is the idea. I don't do that because it will be ugly implementation IMHO).

My fork (branch robbinespu.gitlab.io)  contains lots of modifications but it solely for my own setup. So it won't working well if you take it. But you can take a look my implementation and adjust with your setup. The current dark-mode on my website use font-awesome icon. The upstream (this repo by athul) using feather-icons, i have discuss with him to moving forward and use lucide-icon too. I already done it on my website. If anyone interested, take a look on it and submit patch to upstream, else need wait for me to submit it when I am free. This should be great PR for starters by forking upstream, study my changes, implement it back on a branch and submit for PR.

(sorry, i added more discussion rather than focus on the topic. I just want to hint anyone to involve with this project too 😄)

**Comment by g-pacheco** [comment]
Hello @RobbiNespu,

Thanks very much for your comprehensive answer, and apologies for my late reply. 

Yes, I had seen #30.  To make it short, I really cannot see what is the "issue" with your solution. In my view, it does achieve the requested aim. However, I am sure that other can see things that I cannot.

Anyhow, I hope this will be implemented soon :)  But I will try to follow what you suggested once again.

Thanks a lot, George.

**Comment by athul** [comment]
Closing due to #36
