### ISSUE TITLE
 Google analytics integration

### ISSUE THREAD

**Issue by vinayrkumar** [athul/archie#4]
Hi , should adding the following in the config work ? 
# Your Google analytics code.
googleAnalytics = "UA-123-45"
Or is the GA integration still not available in this theme ?

-Thanks

**Comment by athul** [comment]
It should basically since Hugo has an inbuilt integration for adding Google Analytics Scripts and it's used in the theme too,
```toml
googleAnalytics = "UA-123-45"
```
Should work since
https://github.com/athul/archie/blob/d4d89535c8b1a2a8aca0b748a367c5c6cd253f85/themes/archie/layouts/partials/footer.html#L8-L11

is present here

**Comment by vinayrkumar** [comment]
Works. It was incorrect GA setup. Thanks
