### ISSUE TITLE
Trouble deploying theme on Netlify

### ISSUE THREAD

**Issue by jmwoliver** [athul/archie#46]
Hello! This is an issue with myself, probably not your theme. I am having trouble getting the CSS and JS to render when I deploy my website to Netlify.

I have your theme forked:
https://github.com/jmwoliver/archie

And I am importing it as a submodule to my website:
https://github.com/jmwoliver/website

I then hooked it into Netlify to deploy from that repo. That is deployed here:
https://competent-goodall-6e9101.netlify.app/

Looking at the console logs, it looks like it can't get the JS (and I'm assuming the CSS):
```bash
Loading failed for the <script> with source “https://jmw.sh/js/feather.min.js”. [competent-goodall-6e9101.netlify.app:18:1](https://competent-goodall-6e9101.netlify.app/)
Loading failed for the <script> with source “https://jmw.sh/js/themetoggle.js”. [competent-goodall-6e9101.netlify.app:49:1](https://competent-goodall-6e9101.netlify.app/)
Uncaught ReferenceError: feather is not defined
    <anonymous> https://competent-goodall-6e9101.netlify.app/:100
```

My `baseURL` in `config.toml` is `https://jmw.sh/`, but I haven't done the DNS stuff to route the custom domain to the Netlify address, I was waiting to do that until I got this issue figured out. Could that be my problem, I need to route it first?

Sorry for the lame questions, I'm new to Hugo and deploying on Netlify and using a custom domain, so I'm not sure where the disconnect is. Any help would be appreciated! (P.S. your theme is great, I really like how it looks 😄)

What it looks ilke:
<img width="1728" alt="Screen Shot 2022-02-18 at 9 58 22 AM" src="https://user-images.githubusercontent.com/17369271/154707049-67bf127a-b37c-436c-9176-475ab2b21ba4.png">

What it should look like:
<img width="1728" alt="Screen Shot 2022-02-18 at 9 58 28 AM" src="https://user-images.githubusercontent.com/17369271/154707078-e4c178b2-59ec-486e-81bb-b82687eb6635.png">

**Comment by jmwoliver** [comment]
Once I set up all the DNS records to route everything to jmw.sh and let it propagate, it started working. Nothing to see here, thanks again for the great theme. 😄

**Comment by athul** [comment]
Glad that you figured it out 🔥 . I didn't see this issue 😅 , really sorry
