### ISSUE TITLE
Tags do not work

### ISSUE THREAD

**Issue by MaxScame** [athul/archie#6]
Tried to run the code from the "[site](https://github.com/athul/archie/tree/64ff76d755e64e10a58a4c52dbb68acc0032d2a7)" branch through the `hugo server -D` and tags do not worked well.
Have you seen anything like this?
![image](https://user-images.githubusercontent.com/46719548/86540114-1a006380-bf0b-11ea-8d68-1553dd01ef5a.png)

---
Hugo: v.0.73
OS: Windows 10 Enterprise x64

**Comment by athul** [comment]
![Screen Shot 2020-07-06 at 12 43 41 AM](https://user-images.githubusercontent.com/40897573/86540304-c0576380-bf21-11ea-98bb-a0ecf1033592.png)

**Comment by athul** [comment]
Great to a mk enthusiast here 🎉

**Comment by athul** [comment]
I just updated to Hugo to 0.73, It doesn't work. I'll try to bring up a patch

**Comment by MaxScame** [comment]
Thanks for all!
I've also just checked, It's working fine after downgrade to v.68.3
![image](https://user-images.githubusercontent.com/46719548/86540488-76b14d80-bf0e-11ea-9317-9b7bab724482.png)

**Comment by athul** [comment]
Found the [cause](https://github.com/gohugoio/hugo/issues/6911)

**Comment by athul** [comment]
@MaxScame This is a new update and needed to be documented by the Hugo Team. It'll take time since this is a breaking change

**Comment by samhattangady** [comment]
I used the default `list.html` page for `term.html` and that worked for me.
Have raised a PR. Might help others as well.
