### ISSUE TITLE
Mathjax Support

### ISSUE THREAD

**Issue by samp42** [athul/archie#74]
It seems mathjax requires the inclusion of a script to work, so I did 😃
![image](https://user-images.githubusercontent.com/26767411/206821930-a4cb4fa2-026c-41e6-937a-19a9312d3fd9.png)

Ready to make a PR if it's approved

**Comment by athul** [comment]
Please go ahead 😄

**Comment by samp42** [comment]
I added KaTeX support! I can't push my new branch tho...

**Comment by athul** [comment]
Can you elaborate the issue?

**Comment by samp42** [comment]
I am not authorized to push to your repo 😅

**Comment by athul** [comment]
Ah okay. So make a fork of this repo, create a new branch and push to that branch or just push to the main branch and send a PR :)

**Comment by namelessenko** [comment]
> It seems mathjax requires the inclusion of a script to work, so I did 😃 ![image](https://user-images.githubusercontent.com/26767411/206821930-a4cb4fa2-026c-41e6-937a-19a9312d3fd9.png)
> 
> Ready to make a PR if it's approved

But it seems that there is some problem with a rendering of a matrices. Matrices are rendered without transfers of rows.
<img width="382" alt="Screenshot 2023-06-11 at 13 21 52" src="https://github.com/athul/archie/assets/82897774/a436aa2e-53e9-4854-8146-b65d0505b518">
I have already changed the version of MathJax, but it doesn't help. What do you reckon?
