### ISSUE TITLE
How can I enabled Google Analytics and Disqus ?

### ISSUE THREAD

**Issue by ysnacrk** [athul/archie#8]
Hi, I am new hugo and I like your theme. I use for my personal blog and I dont know how can enable Google A. and Disqus. I read som documents but I couldnt . Any suggestion for enable ?

**Comment by ysnacrk** [comment]
I find these docs and it help me

- https://gohugo.io/templates/internal/ 

Sorry for my ignorance

**Comment by athul** [comment]
Hey, I'm sorry for the Late Reply. The time was like 1 am here when you opened the Issue. It's great that you found the docs. ATM Disqus isn't supported but hey it's always hackable for your needs
